# Favicon
favicon: 'theme-doku/img/favicon.ico'

# --------------------
# Navbar
# --------------------
navbar:
  # The URL of Logo which will be shown at navbar
  logo: 'theme-doku/img/logo.png'
  # If you Logo has no text, you can add title next to your logo.
  # Leave it as an empty string if you don't have
  logo_text: 'Malagu'

# --------------------
# Sidebar Items
# --------------------
sidebar:
  zh-CN: # 语言。

github:
  repo: cellbang/malagu-docs
  edit_on_github: true # true / false
